apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    name: nodeport-label
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30033 
    protocol: TCP
