name: Hello World

on: 
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the 'main' branch
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  hello:
    runs-on: ubuntu-latest  # Defines the runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out the repository
